// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnLSkR_wTKNsjS2olFSrH4kkNJjeIyCC8',
    appId: '1:486426342355:web:72c47c4362255c32cbb526',
    messagingSenderId: '486426342355',
    projectId: 'flutterauthen-15053',
    authDomain: 'flutterauthen-15053.firebaseapp.com',
    storageBucket: 'flutterauthen-15053.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7d2RqNW1EYn9bfBofvxhne_oNOkwboTw',
    appId: '1:486426342355:android:f30b63c99f1f3e6bcbb526',
    messagingSenderId: '486426342355',
    projectId: 'flutterauthen-15053',
    storageBucket: 'flutterauthen-15053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0fr60XeqMmHRFJLp6xmBGSO45UMg01kI',
    appId: '1:486426342355:ios:281cd08938f1543acbb526',
    messagingSenderId: '486426342355',
    projectId: 'flutterauthen-15053',
    storageBucket: 'flutterauthen-15053.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0fr60XeqMmHRFJLp6xmBGSO45UMg01kI',
    appId: '1:486426342355:ios:dcbca3eb626b3c81cbb526',
    messagingSenderId: '486426342355',
    projectId: 'flutterauthen-15053',
    storageBucket: 'flutterauthen-15053.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
